### ISSUE TITLE
Code for Frequency spectrum in Fig. 1

### ISSUE THREAD

**Issue by DachunKai** [Linwei-Chen/FADC#2]
Wonderful work! Could you provide some code snippets for analysing the different patches frequency spectrum in Fig.1 in the paper.

**Comment by Linwei-Chen** [comment]
Thanks for your interest! You can refer to the papers "Fast Training of Convolutional Networks through FFTs" and "HOW DO VISION TRANSFORMERS WORK?" to analyze the frequency of kernels and features.
