### ISSUE TITLE
Adaptive Kernel 中 adaptive_weight 如何产生的？

### ISSUE THREAD

**Issue by weihualiuhupituzi** [Linwei-Chen/FADC#21]
作者您好，请教一下，在Adaptive Kernel 部分，代码中AdaptiveDilatedConv() 类的forward中，通过下面这行代码：
adaptive_weight = self.weight.unsqueeze(0).repeat(b, 1, 1, 1, 1) 直接获取到了自适应权重，请问self.weight具体指代的是哪个卷积的权重呢？如何在代码中体现出来的？十分感谢！

**Comment by Linwei-Chen** [comment]
感谢对我们工作的关注，self.weight是AdaptiveDilatedConv本身的权重，在使用父类初始化时得到，super().__init__(*args, **kwargs) 时得到。
