### ISSUE TITLE
权重加载报错

### ISSUE THREAD

**Issue by jwx15** [Linwei-Chen/FADC#4]
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Linwei-Chen** [comment]
Can you provide more details?

**Comment by jwx15** [comment]
我跑的推理，从mmsegmentation复制的代码image_demo.py
错误
(fadc) ***@***.***:~/work/FADC$ python image_demo.py /home/wk2023/work/FADC/rabbit.jpg /home/wk2023/work/FADC/configs/FADC/upernet_R50_FADC_512_160k_ade20k.py /home/wk2023/work/FADC/weight/best_mIoU_iter_160000.pth
/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
&nbsp; warnings.warn(
load checkpoint from local path: /home/wk2023/work/FADC/weight/best_mIoU_iter_160000.pth
Traceback (most recent call last):
&nbsp; File "/home/wk2023/work/FADC/image_demo.py", line 47, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/home/wk2023/work/FADC/image_demo.py", line 31, in main
&nbsp; &nbsp; model = init_segmentor(args.config, args.checkpoint, device=args.device)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmseg/apis/inference.py", line 34, in init_segmentor
&nbsp; &nbsp; checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 617, in load_checkpoint
&nbsp; &nbsp; checkpoint = _load_checkpoint(filename, map_location, logger)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 552, in _load_checkpoint
&nbsp; &nbsp; return CheckpointLoader.load_checkpoint(filename, map_location, logger)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 299, in load_checkpoint
&nbsp; &nbsp; return checkpoint_loader(filename, map_location)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 318, in load_from_local
&nbsp; &nbsp; checkpoint = torch.load(filename, map_location=map_location)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/torch/serialization.py", line 705, in load
&nbsp; &nbsp; with _open_zipfile_reader(opened_file) as opened_zipfile:
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/torch/serialization.py", line 243, in __init__
&nbsp; &nbsp; super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

网上搜这个错误说是权重问题
image_demo.py
# Copyright (c) OpenMMLab. All rights reserved.
from argparse import ArgumentParser

from mmcv.cnn.utils.sync_bn import revert_sync_batchnorm

from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
from mmseg.core.evaluation import get_palette
import models
import decode_heads

def main():
&nbsp; &nbsp; parser = ArgumentParser()
&nbsp; &nbsp; parser.add_argument('img', help='Image file')
&nbsp; &nbsp; parser.add_argument('config', help='Config file')
&nbsp; &nbsp; parser.add_argument('checkpoint', help='Checkpoint file')
&nbsp; &nbsp; parser.add_argument('--out-file', default="result.jpg", help='Path to output file')
&nbsp; &nbsp; parser.add_argument(
&nbsp; &nbsp; &nbsp; &nbsp; '--device', default='cuda:0', help='Device used for inference')
&nbsp; &nbsp; parser.add_argument(
&nbsp; &nbsp; &nbsp; &nbsp; '--palette',
&nbsp; &nbsp; &nbsp; &nbsp; default='cityscapes',
&nbsp; &nbsp; &nbsp; &nbsp; help='Color palette used for segmentation map')
&nbsp; &nbsp; parser.add_argument(
&nbsp; &nbsp; &nbsp; &nbsp; '--opacity',
&nbsp; &nbsp; &nbsp; &nbsp; type=float,
&nbsp; &nbsp; &nbsp; &nbsp; default=0.5,
&nbsp; &nbsp; &nbsp; &nbsp; help='Opacity of painted segmentation map. In (0, 1] range.')
&nbsp; &nbsp; args = parser.parse_args()

&nbsp; &nbsp; # build the model from a config file and a checkpoint file
&nbsp; &nbsp; model = init_segmentor(args.config, args.checkpoint, device=args.device)
&nbsp; &nbsp; if args.device == 'cpu':
&nbsp; &nbsp; &nbsp; &nbsp; model = revert_sync_batchnorm(model)
&nbsp; &nbsp; # test a single image
&nbsp; &nbsp; result = inference_segmentor(model, args.img)
&nbsp; &nbsp; # show the results
&nbsp; &nbsp; show_result_pyplot(
&nbsp; &nbsp; &nbsp; &nbsp; model,
&nbsp; &nbsp; &nbsp; &nbsp; args.img,
&nbsp; &nbsp; &nbsp; &nbsp; result,
&nbsp; &nbsp; &nbsp; &nbsp; get_palette(args.palette),
&nbsp; &nbsp; &nbsp; &nbsp; opacity=args.opacity,
&nbsp; &nbsp; &nbsp; &nbsp; out_file=args.out_file)


if __name__ == '__main__':
&nbsp; &nbsp; main()


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linwei-Chen/FADC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linwei-Chen/FADC] 权重加载报错 (Issue #4)





 
Can you provide more details?

**Comment by Linwei-Chen** [comment]
Our code is based on mmsegmentation==0.25.0. You may try using the corresponding code from this version.

**Comment by jwx15** [comment]
ok, I will try it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linwei-Chen/FADC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linwei-Chen/FADC] 权重加载报错 (Issue #4)





 
Our code is based on mmsegmentation==0.25.0. You may try using the corresponding code from this version.

**Comment by jwx15** [comment]
(fadc) ***@***.***:~/work/FADC$ python image_demo.py /home/wk2023/work/FADC/rabbit.jpg /home/wk2023/work/FADC/configs/FADC/upernet_R50_FADC_512_160k_ade20k.py /home/wk2023/work/FADC/weight/best_mIoU_iter_160000.pth
/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
&nbsp; warnings.warn(
load checkpoint from local path: /home/wk2023/work/FADC/weight/best_mIoU_iter_160000.pth
Traceback (most recent call last):
&nbsp; File "/home/wk2023/work/FADC/image_demo.py", line 40, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/home/wk2023/work/FADC/image_demo.py", line 27, in main
&nbsp; &nbsp; model = init_segmentor(args.config, args.checkpoint, device=args.device)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmseg/apis/inference.py", line 34, in init_segmentor
&nbsp; &nbsp; checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 617, in load_checkpoint
&nbsp; &nbsp; checkpoint = _load_checkpoint(filename, map_location, logger)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 552, in _load_checkpoint
&nbsp; &nbsp; return CheckpointLoader.load_checkpoint(filename, map_location, logger)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 299, in load_checkpoint
&nbsp; &nbsp; return checkpoint_loader(filename, map_location)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 318, in load_from_local
&nbsp; &nbsp; checkpoint = torch.load(filename, map_location=map_location)
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/torch/serialization.py", line 705, in load
&nbsp; &nbsp; with _open_zipfile_reader(opened_file) as opened_zipfile:
&nbsp; File "/home/wk2023/anaconda3/envs/fadc/lib/python3.9/site-packages/torch/serialization.py", line 243, in __init__
&nbsp; &nbsp; super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linwei-Chen/FADC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linwei-Chen/FADC] 权重加载报错 (Issue #4)





 
Our code is based on mmsegmentation==0.25.0. You may try using the corresponding code from this version.

**Comment by jwx15** [comment]
我尝试了下直接加载也报错，而且cuda版本和你给的一致
import torch
import torch.version

# 指定检查点文件的路径
checkpoint_path = '/home/wk2023/work/FADC/weight/best_mIoU_iter_160000.pth'
print(torch.__version__)
try:
&nbsp; &nbsp; # 尝试加载检查点文件
&nbsp; &nbsp; checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))
&nbsp; &nbsp; print("Checkpoint loaded successfully!")
except Exception as e:
&nbsp; &nbsp; # 如果加载失败，打印错误信息
&nbsp; &nbsp; print(f"Failed to load checkpoint: {e}")








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linwei-Chen/FADC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linwei-Chen/FADC] 权重加载报错 (Issue #4)





 
Our code is based on mmsegmentation==0.25.0. You may try using the corresponding code from this version.

**Comment by Linwei-Chen** [comment]
https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory

It seems that this issue occurs when the file is not downloaded completely.

**Comment by jwx15** [comment]
I downloaded it from Baidu Netdisk, and I've tried twice, but it failed both times. Could you please send me a copy of the weight file directly, via email?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月24日(星期三) 晚上9:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linwei-Chen/FADC] 权重加载报错 (Issue #4)















https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory

似乎在文件未完全下载时会出现此问题。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:<陈林伟/ FA ADC /议题/ 4 / ***@***.***和&gt;

**Comment by Linwei-Chen** [comment]
I will check and update the checkpoint. Thank you for the reminder.

**Comment by Linwei-Chen** [comment]
https://pan.baidu.com/s/1uGNefkH1IpYvMZ6cmq5tXw?pwd=CVPR

Is this ok?

**Comment by jwx15** [comment]
谢谢你的帮助，问题已解决
