### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by dys-master** [Linwei-Chen/FADC#6]
你好，我想查看AdaptiveDilatedConv的输出，当我设置kernel decompose为none时，它和普通卷积类似，能够正常输出，但是当我设置kernel decompose为both，给它传递一样的参数却会出现错误，总是告诉我形状不匹配，比如我设置输出通道是64，会出现128与64不匹配的错误，设为32，会出现64与32不匹配的错误，请问我该如何解决这个问题，谢谢

**Comment by Linwei-Chen** [comment]
我估计是因为你的卷积input和output channel不一致；在对卷积核逐通道、逐核做调整的过程出现了不匹配，这部分可能有bug，您可以打印一下c_att, f_att 的形状与kernel的形状做检查；您可以提供一下详细信息，方便大家讨论

**Comment by Linwei-Chen** [comment]
维度不匹配的问题已经得到解决，是bias的形状不对导致的，目前已经更新！
https://github.com/Linwei-Chen/FADC/blob/main/FADC_only/conv_custom.py
