### ISSUE TITLE
About AdaDR

### ISSUE THREAD

**Issue by LMMMEng** [Linwei-Chen/FADC#8]
Hi, thanks for your excellent work!

I noticed that the paper states that AdaDR can assign a different dilation rate to each pixel. However, upon reviewing the code, it appears that AdaDR is finally implemented using deform_conv2d, which means each channel still shares the same convolution kernel. Could you please clarify how to achieve per-pixel dilation rates, as described in the paper?

**Comment by Linwei-Chen** [comment]
Thanks for your interest! Actually, AdaDR in FADC is similar to deformable convolution. The difference is that AdaDR predicts the dilation (1xHxW), while deformable convolution predicts the offset (2xKxHxW). In the code, we use the variable name "offset" to represent the predicted dilation.

**Comment by LMMMEng** [comment]
Thank you for your response. Actually, the distinction between AdaDR and DCN lies in the fact that deformable computation in AdaDR is based on a template [[-1, -1, -1, 0, -1, 1, 0, -1, 0, 0, 0, 1, 1, -1, 1, 0, 1,1]]. For instance, the [-1, 0] indicates that the weight at the corresponding position can only shift upward vertically, with no offset for the central point. Am I correct?

**Comment by Linwei-Chen** [comment]
Yes, you are right ; )

**Comment by LMMMEng** [comment]
Thanks! Very solid work.
